### ISSUE TITLE
Setup instructions do not work

### ISSUE THREAD

**Issue by timothyjoh** [wonderwhy-er/ChatGPTServerCommander#1]
I could get the server running locally, but I cannot get ChatGPT to import the OpenAPI schema. 

Instructions are a bit out of order as well, and not clear

**Comment by timothyjoh** [comment]
I was a bit wrong, I got the URL input wrong, but the instructions need some help, I might make a PR

**Comment by wonderwhy-er** [comment]
Hey Timothy Johnson!
Thanks for trying and posting the issue.
It would be valuable to see where you encountered issues so I can improve that part.
